### ISSUE TITLE
platform/windows.js fails to initialize if there is no Edge browser in the system

### ISSUE THREAD

**Issue by eugene-stepanov** [bitovi/launchpad#82]
If there is no **Edge** browser in the system then **platform/windows.js** throws an exception below during initialization:
## TypeError: Path must be a string. Received undefined.

I've got it on:
- Windows 10 Enterprise 2016 LTSB
- Node - v8.1.3
- Gulp - v3.9.1

**Comment by andrejewski** [comment]
Closed by #83
