### ISSUE TITLE
Missing edge

### ISSUE THREAD

**Issue by kobleistvan** [bitovi/launchpad#84]
Hi. Just debugged the source code for about 4 hours to find out the issue I had:

launchpad/lib/local/platform/windows.js

Microsoft.MicrosoftEdge folder CAN be missing on corporate laptops. Thus, it returns undefined, and generates a TypeError. This is bad, because it tries to run Edge, where it doesn't exist. As this package is a main dependency for polymer's web-component-tester module, it breaks the polymer test functionality. Please fix :)

**Comment by andrejewski** [comment]
Closing in favor of existing issue: #82. Please provide a better description of the exception you are seeing in that issue, in particular which line in [this file](https://github.com/bitovi/launchpad/blob/master/lib/local/platform/windows.js) the exception is on.
